=== DariaValevataya/task2/src/main/resources/card.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:element name="oldCards">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="baseOldCard" type="BaseOldCardType" maxOccurs="50"  />
        <xs:element name="specialOldCard" type="SpecialOldCardType" minOccurs="0" maxOccurs="50"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="BaseOldCardType">
    <xs:sequence>
      <xs:element name="type" default="Ordinary">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Greeting"/>
            <xs:enumeration value="Promotional"/>
            <xs:enumeration value="Ordinary"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="country" >
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Russia"/>
            <xs:enumeration value="Belarus"/>
            <xs:enumeration value="Ukraine"/>
            <xs:enumeration value="Kazakhstan"/>
            <xs:enumeration value="Georgia"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:length value="12"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="thema" type="xs:string" use="required"/>
    <xs:attribute name="year" type="xs:gYear" use="required"/>
    <xs:attribute name="author">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="[A-Z][a-z]+ [A-Z]\."/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="SpecialOldCardType">
    <xs:complexContent>
      <xs:extension base="BaseOldCardType">
        <xs:sequence>
          <xs:element name="valuable" default="Thematic">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Historical"/>
                <xs:enumeration value="Collectible"/>
                <xs:enumeration value="Thematic"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== DariaValevataya/task2/xml/card.xml
<?xml version="1.0" encoding="UTF-8"?>
<oldCards xsi:noNamespaceSchemaLocation="card.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <baseOldCard id="45Ñ€fgh90fh9f" thema="Landscape" year="2014" author="Matveev A.">
    <type>Promotional</type>
    <country>Belarus</country>
  </baseOldCard>
  <baseOldCard id="sdfo09sdf87d"  year="2022" thema="Sport">
    <type>Ordinary</type>
    <country>Russia</country>
  </baseOldCard>
  <baseOldCard id="sew43k56l45k" author="Karakozov R." thema="People"   year="2019">
    <type>Greeting</type>
    <country>Georgia</country>
  </baseOldCard>
  <baseOldCard id="podf8g90dofg" thema="Sport" year="2024" author="Sergeev D.">
    <type>Greeting</type>
    <country>Georgia</country>
  </baseOldCard>
  <baseOldCard id="iodfg94jh45h"  year="2022" thema="Nature">
    <type>Promotional</type>
    <country>Ukraine</country>
  </baseOldCard>
  <baseOldCard id="453ojhd345j4" thema="Religion" author="Smirnov A." year="2020" >
    <type>Ordinary</type>
    <country>Kazakhstan</country>
  </baseOldCard>
  <baseOldCard id="sdf983jfiro8" thema="Landscape" year="2019" author="Timofeev G.">
    <type>Ordinary</type>
    <country>Kazakhstan</country>
  </baseOldCard>
  <baseOldCard id="349dfsf3432d" thema="People" year="2012">
    <type>Ordinary</type>
    <country>Belarus</country>
  </baseOldCard>

  <specialOldCard id="4059fghlgii5"  year="2023" thema="Nature" author="Vasilevskaya A.">
    <type>Ordinary</type>
    <country>Belarus</country>
    <valuable>Historical</valuable>
  </specialOldCard>
  <specialOldCard id="dfu5847udf8e" thema="People" year="2021">
    <type>Greeting</type>
    <country>Russia</country>
    <valuable>Thematic</valuable>
  </specialOldCard>
  <specialOldCard id="kfjg98dfg8df" thema="Sport"  author="Radevich A." year="2021" >
    <type>Promotional</type>
    <country>Kazakhstan</country>
    <valuable>Thematic</valuable>
  </specialOldCard>
  <specialOldCard id="we943ko745is" thema="People" year="2022">
    <type>Promotional</type>
    <country>Kazakhstan</country>
    <valuable>Collectible</valuable>
  </specialOldCard>
  <specialOldCard id="po4562psdfqw"  year="2022" author="Gavrilenko U." thema="Religion">
    <type>Promotional</type>
    <country>Ukraine</country>
    <valuable>Historical</valuable>
  </specialOldCard>
  <specialOldCard id="xcv67bnm87nb" thema="Architecture" year="2024">
    <type>Promotional</type>
    <country>Belarus</country>
    <valuable>Historical</valuable>
  </specialOldCard>
  <specialOldCard id="nmlk560xc98v" thema="Landscape" year="2020" author="Ulasevich S.">
    <type>Ordinary</type>
    <country>Russia</country>
    <valuable>Historical</valuable>
  </specialOldCard>
  <specialOldCard id="rfbn45xz45bn" thema="Sport" year="2019">
    <type>Promotional</type>
    <country>Georgia</country>
    <valuable>Collectible</valuable>
  </specialOldCard>
</oldCards>
